/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.util.Calendar;
import java.util.Locale;
import model.Calendrier;

/**
 *
 * @author Rasem
 */
public class PanelChoixAnnee extends javax.swing.JPanel {

    Calendrier c;
    int current_year;

    /**
     * Creates new form PanelChoixAnnee
     */
    public PanelChoixAnnee() {Calendar cal = Calendar.getInstance(Locale.FRANCE);
        current_year=cal.get(Calendar.YEAR);
        initComponents();
        ChoixAnnee.removeAllItems();
        for (int i = current_year;i <= current_year + 10; i++) {
        ChoixAnnee.addItem(i+" - "+(i+1));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelAnnee = new javax.swing.JLabel();
        ChoixAnnee = new javax.swing.JComboBox();

        LabelAnnee.setText("jLabel1");

        ChoixAnnee.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ChoixAnnee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoixAnneeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ChoixAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(LabelAnnee)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChoixAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelAnnee))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ChoixAnneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoixAnneeActionPerformed
        int index = ChoixAnnee.getSelectedIndex();
        c = new Calendrier(current_year + index);
        LabelAnnee.setText(c.getAnnee() + "");
    }//GEN-LAST:event_ChoixAnneeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ChoixAnnee;
    private javax.swing.JLabel LabelAnnee;
    // End of variables declaration//GEN-END:variables
}
